function progress = startTsEPSIProgress(showProgress, titleText)
%STARTTSEPSIPROGRESS Create the SLOW-MRSI progress window.
% SLOW-MRSI reconstruction package
% Author/Maintainer: Dr. Guodong Weng, University of Bern
% Date: 2026-07-04

progress = struct('enabled', false, 'h', [], 'stageText', [], 'detailText', [], ...
    'blockText', [], 'overallText', [], 'barPatch', [], 'actionButton', []);

if ~showProgress
    return
end

try
    progress.h = figure('Name', titleText, ...
        'NumberTitle', 'off', ...
        'IntegerHandle', 'off', ...
        'HandleVisibility', 'off', ...
        'MenuBar', 'none', ...
        'ToolBar', 'none', ...
        'Resize', 'off', ...
        'Position', [200, 200, 560, 220], ...
        'CloseRequestFcn', 'setappdata(gcbf,''canceling'',1)');
    setappdata(progress.h, 'canceling', 0);

    progress.stageText = uicontrol(progress.h, 'Style', 'text', ...
        'String', 'Starting...', ...
        'HorizontalAlignment', 'left', ...
        'FontWeight', 'bold', ...
        'FontSize', 11, ...
        'Position', [24, 174, 512, 24]);

    progress.detailText = uicontrol(progress.h, 'Style', 'text', ...
        'String', '', ...
        'HorizontalAlignment', 'left', ...
        'FontSize', 10, ...
        'Position', [24, 142, 512, 28]);

    progress.blockText = uicontrol(progress.h, 'Style', 'text', ...
        'String', 'Block: 0.0%', ...
        'HorizontalAlignment', 'left', ...
        'FontSize', 10, ...
        'Position', [24, 108, 250, 22]);

    progress.overallText = uicontrol(progress.h, 'Style', 'text', ...
        'String', 'Overall: 0.0%', ...
        'HorizontalAlignment', 'right', ...
        'FontSize', 10, ...
        'Position', [286, 108, 250, 22]);

    barAxes = axes('Parent', progress.h, ...
        'Units', 'pixels', ...
        'Position', [24, 72, 512, 20], ...
        'XLim', [0 1], ...
        'YLim', [0 1], ...
        'XTick', [], ...
        'YTick', [], ...
        'Box', 'on');
    progress.barPatch = patch(barAxes, [0 0 0 0], [0 1 1 0], [0.10 0.65 0.20], ...
        'EdgeColor', 'none');

    progress.actionButton = uicontrol(progress.h, 'Style', 'pushbutton', ...
        'String', 'Cancel', ...
        'Position', [430, 24, 106, 30], ...
        'Callback', 'setappdata(gcbf,''canceling'',1)');

    progress.enabled = true;
catch ME
    warning('MATLAB:TsEPSIProgressUnavailable', ...
        'Progress window could not be created (%s). Continuing without it.', ME.message);
end
end
